import 'zone.js';
import '@angular/localize/init';
import { bootstrapApplication } from '@angular/platform-browser';

// Vendor package styles, imported here (JS module resolver handles bare
// specifiers) rather than @import'ed inside app.scss (Vite's dev sass importer
// can't canonicalize bare specifiers). Order matters: vendor first, theme last.
import 'bootstrap/dist/css/bootstrap.min.css';
import 'ngx-toastr/toastr';
import 'swiper/css';
import 'swiper/swiper-bundle.css';
// Global Fastkart theme styles. We import the PRE-COMPILED css (generated by the
// `styles` npm script via dart-sass), NOT app.scss directly: analog()'s SSR dev
// server breaks Vite's sass importer for global scss — relative @imports fail
// with "canonicalize() must return a URL" (admin's non-SSR angular() plugin
// doesn't hit this). dart-sass compiles it identically to the production build;
// the css's url()s are absolute (/assets/images/...) so they resolve untouched.
import './scss/app.gen.css';

import { App } from './app/app';
import { appConfig } from './app/app.config';

bootstrapApplication(App, appConfig).catch(err => console.error(err));
